import type {HomepageSlide,HomepageSlideInput} from '$lib/cms/home/types';
import {getSql} from '$lib/server/neonClient';
type Row={id:number;enabled:boolean|null;sort_order:number|null;title_el:string|null;title_de:string|null;description_el:string|null;description_de:string|null;alt_el:string|null;alt_de:string|null;image_480:string|null;image_960:string|null;image_1920:string|null;image_fallback:string|null;created_at:string|null;updated_at:string|null};
function map(r:Row):HomepageSlide{const now=new Date().toISOString();return{id:Number(r.id),enabled:r.enabled!==false,sortOrder:Number(r.sort_order??0),title:{el:r.title_el||'',de:r.title_de||r.title_el||''},description:{el:r.description_el||'',de:r.description_de||r.description_el||''},alt:{el:r.alt_el||r.title_el||'',de:r.alt_de||r.title_de||r.alt_el||r.title_el||''},image480:r.image_480||'',image960:r.image_960||'',image1920:r.image_1920||'',imageFallback:r.image_fallback||r.image_1920||r.image_960||r.image_480||'',createdAt:r.created_at||now,updatedAt:r.updated_at||now}}
function values(s:HomepageSlideInput){return[s.enabled,s.sortOrder,s.title.el||'',s.title.de||s.title.el||'',s.description.el||'',s.description.de||'',s.alt.el||s.title.el||'',s.alt.de||s.alt.el||s.title.de||s.title.el||'',s.image480||'',s.image960||'',s.image1920||'',s.imageFallback||s.image1920||s.image960||s.image480||''] as const}
export async function listHomepageSlides(includeDisabled=false){const rows=includeDisabled?await getSql()`SELECT * FROM homepage_slides ORDER BY sort_order,id`:await getSql()`SELECT * FROM homepage_slides WHERE enabled=TRUE ORDER BY sort_order,id`;return rows.map(r=>map(r as Row))}
export async function getHomepageSlide(id:number){if(!Number.isFinite(id))return null;const rows=await getSql()`SELECT * FROM homepage_slides WHERE id=${id} LIMIT 1`;return rows[0]?map(rows[0] as Row):null}
export async function createHomepageSlide(s:HomepageSlideInput){const v=values(s);const rows=await getSql()`INSERT INTO homepage_slides(enabled,sort_order,title_el,title_de,description_el,description_de,alt_el,alt_de,image_480,image_960,image_1920,image_fallback,updated_at) VALUES(${v[0]},${v[1]},${v[2]},${v[3]},${v[4]},${v[5]},${v[6]},${v[7]},${v[8]},${v[9]},${v[10]},${v[11]},NOW()) RETURNING *`;return map(rows[0] as Row)}
export async function updateHomepageSlide(id:number,s:HomepageSlideInput){if(!Number.isFinite(id))throw new Error('Invalid homepage slide id');const v=values(s);const rows=await getSql()`UPDATE homepage_slides SET enabled=${v[0]},sort_order=${v[1]},title_el=${v[2]},title_de=${v[3]},description_el=${v[4]},description_de=${v[5]},alt_el=${v[6]},alt_de=${v[7]},image_480=${v[8]},image_960=${v[9]},image_1920=${v[10]},image_fallback=${v[11]},updated_at=NOW() WHERE id=${id} RETURNING *`;if(!rows[0])throw new Error(`Homepage slide "${id}" not found`);return map(rows[0] as Row)}
export async function deleteHomepageSlide(id:number){if(!Number.isFinite(id))return false;return (await getSql()`DELETE FROM homepage_slides WHERE id=${id} RETURNING id`).length>0}
