import type {LinkPayload,LinkSaveInput,StoredLink} from '$lib/cms/links/types';
import {linkPayloadSchema} from '$lib/cms/links/schema';
import {getSql} from '$lib/server/neonClient';
type LinkRow={id:number;name_el:string|null;name_de:string|null;description_html_el:string|null;description_html_de:string|null;url:string|null;logo:string|null;logo_webp:string|null;logo_jpg:string|null;created_at:string|null;updated_at:string|null};
function normalizePayload(input:LinkSaveInput):LinkPayload{const r=linkPayloadSchema.safeParse({name:input.name,descriptionHtml:input.descriptionHtml??{el:'',de:''},url:input.url,logo:input.logo??'',logoVariants:input.logoVariants??{webp:'',jpg:''}});if(!r.success)throw new Error(r.error.issues[0]?.message||'Invalid link data');return r.data}
function map(r:LinkRow):StoredLink{const now=new Date().toISOString();return{id:Number(r.id),name:{el:r.name_el||'',de:r.name_de||''},descriptionHtml:{el:r.description_html_el||'',de:r.description_html_de||''},url:r.url||'',logo:r.logo||r.logo_webp||r.logo_jpg||'',logoVariants:{webp:r.logo_webp||r.logo||'',jpg:r.logo_jpg||''},createdAt:r.created_at||now,updatedAt:r.updated_at||now}}
export async function listLinks(){const rows=await getSql()`SELECT * FROM links ORDER BY id DESC`;return rows.map(r=>map(r as LinkRow))}
export async function getLinkById(id:number){if(!Number.isFinite(id))return null;const rows=await getSql()`SELECT * FROM links WHERE id=${id} LIMIT 1`;return rows[0]?map(rows[0] as LinkRow):null}
export async function upsertLink(input:LinkSaveInput){const p=normalizePayload(input);const logo=p.logo||p.logoVariants?.webp||'';let rows;if(input.id&&Number.isFinite(input.id)){rows=await getSql()`UPDATE links SET name_el=${p.name.el||''},name_de=${p.name.de||''},description_html_el=${p.descriptionHtml.el||''},description_html_de=${p.descriptionHtml.de||''},url=${p.url},logo=${logo},logo_webp=${p.logoVariants?.webp||p.logo||''},logo_jpg=${p.logoVariants?.jpg||''},updated_at=NOW() WHERE id=${input.id} RETURNING *`}else{rows=await getSql()`INSERT INTO links(name_el,name_de,description_html_el,description_html_de,url,logo,logo_webp,logo_jpg,updated_at) VALUES(${p.name.el||''},${p.name.de||''},${p.descriptionHtml.el||''},${p.descriptionHtml.de||''},${p.url},${logo},${p.logoVariants?.webp||p.logo||''},${p.logoVariants?.jpg||''},NOW()) ON CONFLICT(url) DO UPDATE SET name_el=EXCLUDED.name_el,name_de=EXCLUDED.name_de,description_html_el=EXCLUDED.description_html_el,description_html_de=EXCLUDED.description_html_de,logo=EXCLUDED.logo,logo_webp=EXCLUDED.logo_webp,logo_jpg=EXCLUDED.logo_jpg,updated_at=NOW() RETURNING *`}return map(rows[0] as LinkRow)}
export const saveLink=upsertLink;
export async function deleteLink(id:number){if(!Number.isFinite(id))return false;return (await getSql()`DELETE FROM links WHERE id=${id} RETURNING id`).length>0}
